version: 0.0
os: linux
files:
  - source: ./
    destination: /var/www/temp/
hooks:
  BeforeInstall:
    - location: Scripts/PrepareResourceBundle.sh
  AfterInstall:
    - location: Scripts/CopyResourceCode.sh
      timeout: 180
  ApplicationStart:
    - location: Scripts/RunFunctionalTests.sh
      timeout: 3600
  ValidateService:
    - location: Scripts/MonitorService.sh
      timeout: 3600
      runas: ubuntu
